from datetime import datetime

from sqlalchemy import ARRAY, ForeignKey, Text, func
from sqlalchemy.dialects.postgresql import TIMESTAMP
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db import Base


class ProvisionToken(Base):
    """Single-use scoped provisioning token for technicians (§21.3).

    The raw token is a JWT generated by services/token.py.  Only the
    SHA-256 hex digest is stored here so the plaintext never reaches
    the database.
    """

    __tablename__ = "provision_token"

    # SHA-256 hex of the raw JWT
    token_hash: Mapped[str] = mapped_column(Text, primary_key=True)
    # Optional: device this token is pre-scoped to (may be None for unrestricted)
    device_id: Mapped[str | None] = mapped_column(
        Text, ForeignKey("device.device_id"), nullable=True
    )
    # Device IDs this token is allowed to provision (matches JWT payload)
    allowed_device_ids: Mapped[list[str] | None] = mapped_column(ARRAY(Text), nullable=True)
    created_by: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False, server_default=func.now())
    expires_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False)
    used_at: Mapped[datetime | None] = mapped_column(TIMESTAMP(timezone=True), nullable=True)

    device: Mapped["Device | None"] = relationship("Device", back_populates="provision_tokens")


class RevokedJWT(Base):
    """Revoked JWT registry keyed by jti.

    Stores explicit revocations for currently-issued tokens.  Combined with
    User.token_valid_after for efficient bulk invalidation.
    """

    __tablename__ = "revoked_jwt"

    # JWT ID claim
    jti: Mapped[str] = mapped_column(Text, primary_key=True)
    # Token subject (username)
    sub: Mapped[str] = mapped_column(Text, nullable=False)
    reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    revoked_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=func.now()
    )
    expires_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False)
